### PR TITLE
Enable Windows builds on Appveyor

### PR DESCRIPTION
**Pull request by torn4dom4n**
Enable Windows builds on Appveyor

### CODE REVIEW

**Comment by nathansobo** [comment]
@torn4dom4n Hey again... so when I visit the link you added to the README it looks like the build is failing. Am I missing something?

**Comment by torn4dom4n** [comment]
@nathansobo it is an old links beacause someone built `Atom keymap` on Appveyor. You can click to see it.

**Comment by nathansobo** [comment]
@torn4dom4n My question is if I merge this will we have a green badge for AppVeyor? Seems like no. Do I need to do some setup in the repository config to unblock you?

**Comment by torn4dom4n** [comment]
It's not as good as I thought. You can see at https://ci.appveyor.com/project/torn4dom4n/atom-keymap. I will check it again. If it fail, I will close this PR.

**Comment by nathansobo** [comment]
You're also welcome to get it passing, but I realize that might be more work than you have time for.

**Comment by nathansobo** [comment]
Cool. Looks like you're working on it. Thanks! Ping me when you're ready.

**Comment by torn4dom4n** [comment]
@nathansobo I am trying!

**Comment by 50Wliu** [comment]
Try merging from master to pick up keyboard-layout@2.0.1.  That's where the build looks like it's failing.

**Comment by torn4dom4n** [comment]
@50Wliu It is not reason. I will submit an issue to `devtool`.

**Comment by nathansobo** [comment]
I'm not married to dev tool if we want to find a different way of running these specs.

**Comment by torn4dom4n** [comment]
I will close this request! `Mocha` don't work with coffee files on Windows. I will reopen if I solve this issue!

**Pull request closed without merging**
