### PR TITLE
[WIP] Convert coffee to JS

### PR DESCRIPTION
**Pull request by Rokt33r**
- [ ] src
  - [x] command-event
  - [ ] helper
  - [ ] key-binding
  - [ ] keymap-manager
  - [ ] us-keymap
- [ ] spec
  - [ ] helpers-spec
  - [ ] key-binding-spec
  - [ ] keymap-manager-spec
- [ ] benchmark/benchmark
- [ ] gruntfile
- [ ] remove all dependencies related with coffee script

### CODE REVIEW

**Comment by Rokt33r** [comment]
@nathansobo 
I think I should wait until review. I'm afraid if I've gone faraway.
Please check, then I'll fix it and continue the work. 😀

**Comment by nathansobo** [comment]
Hey @Rokt33r. Yikes. Looks like we had a miscommunication on our end. Unfortunately @iolsen's `io-modifier-keyups` branch was not current with `master` when you started your work, and you're going to need to merge master into your branch. I'm really sorry.

**Comment by iolsen** [comment]
Shoot that's my fault. I think the changes since my last merge with master are minor. Let me know if I can help.

**Comment by Rokt33r** [comment]
@nathansobo @iolsen 
I'm okay. 😭 I'll start again from `master` branch after I wake up.
Btw, how should I move the comments? Is there any guidance of it?

**Comment by iolsen** [comment]
I've merged master into `io-modifier-keyups` again so that branch is still (again) the right basis for this conversion.

**Comment by Rokt33r** [comment]
@iolsen Great, I'll pull it again! 😁

**Comment by iolsen** [comment]
Really sorry about that. Thanks for your work on this!

**Comment by Rokt33r** [comment]
I created another branch, https://github.com/atom/atom-keymap/pull/168, to start from `master`.

**Pull request closed without merging**
