### PR TITLE
Coffeelint support

### PR DESCRIPTION
**Pull request by torn4dom4n**
Add coffeelint support!

### CODE REVIEW

**Comment by nathansobo** [comment]
Hey, give me a few sentences explaining what you're doing please. Why should I merge this?

**Comment by nathansobo** [comment]
Okay once this build goes green I'm comfortable merging it.

**Comment by torn4dom4n** [comment]
I think use [Coffeelint](http://www.coffeelint.org) better than [grunt-coffeelint](https://www.npmjs.com/package/grunt-coffeelint), your code cleaner and more consistent, you can see https://travis-ci.org/atom/atom-keymap/builds/168703887. You can control your dependency packages with Dependency Status Badge. And it will consistency with other package in Atom. Do you think so?

**Comment by nathansobo** [comment]
Yeah, makes sense. Just need a green build and I'm happy to merge it.

**Comment by torn4dom4n** [comment]
I will complete it when I can!

**Comment by thomasjo** [comment]
Why are you replacing all valid usage of `@something` with `this.something`?

**Comment by torn4dom4n** [comment]
I checked with Coffeescript.org you can see [before](http://coffeescript.org/#try:%23%20This%20custom%20subclass%20of%20CustomEvent%20exists%20to%20provide%20the%20%3A%3AabortKeyBinding%0A%23%20method%2C%20as%20well%20as%20versions%20of%20the%20%3A%3AstopPropagation%20methods%20that%20record%20the%0A%23%20intent%20to%20stop%20propagation%20so%20event%20bubbling%20can%20be%20properly%20simulated%20for%0A%23%20detached%20elements.%0A%23%0A%23%20CustomEvent%20instances%20are%20exotic%20objects%2C%20meaning%20the%20CustomEvent%20constructor%0A%23%20*must*%20be%20called%20with%20an%20exact%20CustomEvent%20instance.%20We%20work%20around%20this%20fact%0A%23%20by%20building%20a%20CustomEvent%20directly%2C%20then%20injecting%20this%20object%20into%20the%0A%23%20prototype%20chain%20by%20setting%20its%20__proto__%20property.%0Amodule.exports%20%3D%0Aclass%20CommandEvent%20extends%20CustomEvent%0A%20%20keyBindingAborted%3A%20false%0A%20%20propagationStopped%3A%20false%0A%0A%20%20abortKeyBinding%3A%20-%3E%0A%20%20%20%20%40stopImmediatePropagation()%0A%20%20%20%20%40keyBindingAborted%20%3D%20true%0A%0A%20%20stopPropagation%3A%20-%3E%0A%20%20%20%20%40propagationStopped%20%3D%20true%0A%20%20%20%20super%0A%0A%20%20stopImmediatePropagation%3A%20-%3E%0A%20%20%20%20%40propagationStopped%20%3D%20true%0A%20%20%20%20super) and [after](http://coffeescript.org/#try:%23%20This%20custom%20subclass%20of%20CustomEvent%20exists%20to%20provide%20the%20%3A%3AabortKeyBinding%0A%23%20method%2C%20as%20well%20as%20versions%20of%20the%20%3A%3AstopPropagation%20methods%20that%20record%20the%0A%23%20intent%20to%20stop%20propagation%20so%20event%20bubbling%20can%20be%20properly%20simulated%20for%0A%23%20detached%20elements.%0A%23%0A%23%20CustomEvent%20instances%20are%20exotic%20objects%2C%20meaning%20the%20CustomEvent%20constructor%0A%23%20*must*%20be%20called%20with%20an%20exact%20CustomEvent%20instance.%20We%20work%20around%20this%20fact%0A%23%20by%20building%20a%20CustomEvent%20directly%2C%20then%20injecting%20this%20object%20into%20the%0A%23%20prototype%20chain%20by%20setting%20its%20__proto__%20property.%0Amodule.exports%20%3D%0Aclass%20CommandEvent%20extends%20CustomEvent%0A%20%20keyBindingAborted%3A%20false%0A%20%20propagationStopped%3A%20false%0A%0A%20%20abortKeyBinding%3A%20-%3E%0A%20%20%20%20this.stopImmediatePropagation()%0A%20%20%20%20this.keyBindingAborted%20%3D%20true%0A%0A%20%20stopPropagation%3A%20-%3E%0A%20%20%20%20this.propagationStopped%20%3D%20true%0A%20%20%20%20super%0A%0A%20%20stopImmediatePropagation%3A%20-%3E%0A%20%20%20%20this.propagationStopped%20%3D%20true%0A%20%20%20%20super).

**Comment by torn4dom4n** [comment]
Oh I think should update coffeelint rather than `@something` with `this.something`. I will revert all.

**Comment by torn4dom4n** [comment]
@nathansobo I cleaned everything!

**Comment by nathansobo** [comment]
@torn4dom4n Wow. Thanks so much! Awesome work! Please feel free to make similar contributions elsewhere.

**Comment by torn4dom4n** [comment]
:heart:

**Pull request merged**
