### PR TITLE
Enabled support to custom Dvorak-Qwerty keyboard layouts

### PR DESCRIPTION
**Pull request by sergiovilar**
Please see [#12](https://github.com/atom/atom-keymap/issues/12#issuecomment-111155447)

### CODE REVIEW

**Comment by nathansobo** [comment]
Thanks @sergiovilar!

**Comment by sergiovilar** [comment]
@nathansobo I've noticed this commit has been removed from the codebase. There's any reason? Because right now Atom is binded to `com.apple.keylayout.DVORAK-QWERTYCMD` layout which is the Apple layout, but it does not allow custom DVORAK-QWERTY as other code editors does.

**Comment by Ben3eeE** [comment]
@sergiovilar Can you please open an issue for this. It might have accidentally been removed when we did the rewrite for international keyboard support.

Can you also comment what the name of your current keyboard layout is in the issue? And also add instructions on how to setup a custom layout so we can test it out locally.

**Comment by sergiovilar** [comment]
@Ben3eeE as a portuguese speaker I need sometimes to write some latin special characters and Apple's DVORAK-QWERTY layout does not support dead keys, so I've created a custom DVORAK-QWERTY layout in order to have quick access to those characters. The [layout is here](https://www.dropbox.com/s/jpfa9hkmmfbhqzh/Dvorak%20QWERTY%20dead%20keys.keylayout?dl=0) and instructions on how to install can be found [here](http://www.languagegeek.com/keyboard_general/mac_installation1.html).

I've noticed that all references to the dvorak workaround have been removed from the codebase, I'm assuming you guys are giving the responsability to packages?

If so, I took a look into`addKeystrokeResolver` and noticed that the method allows customization so I wrote a little script to translate the QWERTY keys to DVORAK. It seems to be working for now.

If you guys intend to support custom DVORAK-QWERTY layouts natively please me let me know so I can open an issue for that. If not, I can try to create a package.

**Comment by Ben3eeE** [comment]
@sergiovilar The workaround still is there but it checks for exact string now which seems to be the change this PR made to get it working for you earlier:

https://github.com/atom/atom-keymap/blob/a58480827d0b3a880e32817f997c4ac74df4256d/src/helpers.coffee#L222

We do want to support all possible layouts. This workaround has been needed because of a bug in chromium. The bug has since been fixed but the fix has not yet reached us. I believe it will be in the next beta release on chromium so it will take a while before it reaches us. I am open to fix this in atom-keymap in the meantime. Having install instructions in an issue will help us verify that your setup is still working when we intend to remove this workaround once the fix has reached us.

It will help us if you create an issue for it because comments in PRs are hard to track and will be forgotten about 🙂 Or if you want you can open a PR to add this workaround again. It would still be great to have the install instructions documented so we can verify the changes before merging 🙇

Please @mention me once in the new issue and I will take a look as soon as I can.

**Comment by sergiovilar** [comment]
Ok, I'll do that. Thank you!

**Pull request merged**
