### PR TITLE
Improve support for international keyboards

### LINKED ISSUE #35: Right ALT not supported (bad for International Keyboards)
Original issue: https://github.com/atom/atom/issues/1625

---

Use https://atom.io/packages/keyboard-localization until this issue gets fixed (should be in the Blink upstream).

### PR DESCRIPTION
**Pull request by nathansobo**
Closes #35

Now that the new `KeyboardEvent.key` and `KeyboardEvent.code` APIs are available in Chrome, we can finally support international keyboard layouts in core without a building tower of fragile hacks. This isn't as straightforward as I'd hoped, but this PR updates our translation of keyboard events to keystroke strings as follows:

#### On Windows and Linux

The keystroke's primary character is always based on the `.key` property of the keyboard event. If we determine that the `AltGraph` key is depressed via `KeyboardEvent.getModifierState`, we don't render `alt` as part of the keystroke. On Windows, we also don't render `ctrl` as part of the keystroke since `ctrl-alt-` is commonly used as a substitute for the physical `AltGraph` key.

#### On macOS

Like the other platforms, we base the primary character on the `.key` property of the keyboard event.

Because Macs don't have a dedicated `AltGraph` key, we need to be more nuanced about interpreting the user's intent when they use the Mac `⌥` key. If we always interpreted `⌥` to mean `AltGraph`, many `alt-` bindings would become impossible to type on macOS. Instead, we only consider `⌥` to mean `AltGraph` when `KeyboardEvent.key` is in the basic ASCII character range. If `⌥` is used and the typed character is non-ASCII, we use a native node module to determine the non-`⌥`-modified variant of the character based on the physical location of the key (`KeyboardEvent.code`) and the current system keyboard layout.

For example, on a Swiss-German layout, we will resolve `⌥G` keystrokes to `@` rather than `alt-g` because `@` is an ASCII symbol. However, we won't resolve `⌥G` to `©` on a U.S. layout because we consider the ability to bind `alt-g` more important than typing copyright symbols. However, if you *want* to type `©` with `⌥G`, that will work fine as long as there are no existing `alt-g` bindings. As a text editor used to write code, we considered it worthwhile to treat ASCII as a special case and protect the ability to type basic ASCII from any packages that might accidentally shadow those keystrokes with `alt-` bindings.

### Key bindings on non-Latin layouts

If you're using a Greek keyboard on macOS, `⌘Σ` does not exist as a binding. If you type that physical key combination, it actually resolves to `⌘S`, which is the default binding for saving a document.

In Atom, we've tried to copy this behavior. Basically, bindings can be expressed only with Latin characters. So `alt-u` can be bound and so can `alt-ü`, but on non-Latin layouts, keystrokes with modifiers convert the typed character to its equivalent on a U.S. layout.

Apologies if this appears to be a culturally insensitive approach... We're trying to match the expected behavior and it seemed like macOS is a good guide in this respect. Please let us know if we're missing some nuance here.

### CODE REVIEW

**Comment by ccoenen** [comment]
Is there an easy way to "test drive" this change? Can I just download atom alpha and replace the atom-keymap with this change?

**Comment by nathansobo** [comment]
@ccoenen You'll need to build Atom from source at this stage and link the `atom-keymap` module. The list of steps is kinda long due to npm building native dependencies on link.

* `git clone https://github.com/atom/atom-keymap`
* `cd atom-keymap`
* `git checkout ns-mb-localization`
* `apm install`
* `npm link`
* `apm rebuild`
* `cd atom`
* `npm link atom-keymap`
* `atom -d # start atom in dev mode`

You could also wait until this lands on master and build from source without the linking. Or wait for beta.

**Comment by nathansobo** [comment]
Actually, I can publish an Atom branch so you can download a build. What platform are you on?

**Comment by ccoenen** [comment]
downloading them as I type :) Thanks!

**Comment by ccoenen** [comment]
I'll go over all the keys that don't work in 1.10 for me (german keyboard layout) and how it compares to the new version. This is sorted by position on the keybard in english text reading direction.

* `²` and `³` <kbd>AltGr+2</kbd> and <kbd>AltGr+3</kbd> worked before, keeps working
* `{[]}` <kbd>AltGr+7</kbd> through <kbd>AltGr+0</kbd> worked before, keeps working. (You may wonder how one even programs on a german keybard, right now. And you would be right.)
* `\` <kbd>AltGr+ß</kbd> works fine (did not do anything before)
* `@` <kbd>AltGr+Q</kbd> will insert an @ symbol and then `Autoflow: Reflow Selection` my current piece of code. This seems to be two distinct actions, at least from an "undo buffer" point of view. (before it just reflowed with no added @) :boom: but also :+1:
* `€` <kbd>AltGr+E</kbd> worked before, keeps working.
* `~` <kbd>AltGr++</kbd> works fine (did not do anything before) :+1: 
* `|` <kbd>AltGr+<</kbd> worked before, keeps working
* `µ` <kbd>AltGr+M</kbd> works fine (did not do anything before) :+1: 

Overall a VAST improvement for me. The only problem remaining is the @ / Reflow thing and that even comes with a quick remedy (undo removing only the reflow).

I've used the editor for only a few minutes, but my "OMG I CAN'T TYPE THAT" reflexes are already relaxing. I used to <kbd>Ctrl+F</kbd> <kbd>\ </kbd> <kbd>Ctrl+A</kbd> <kbd>Ctrl+C</kbd> <kbd>ESC</kbd> <kbd>Ctrl+V</kbd> to get a `\` into my code. No more! :D

This feels pretty native to me. I hope this holds true to all these other layouts out there!

**Comment by nathansobo** [comment]
@ccoenen What platform are you on? I want to fix the reflow selection problem.

**Comment by ccoenen** [comment]
@nathansobo I added the info to my previous Post: It's Windows 10.

(I'll also remove this post right after posting so you get a notification but everyone else won't have to put up with me forgetting vital information :D )

**Comment by nathansobo** [comment]
Okay, so I've narrowed the reflow issue down to a menu item with `ctrl-alt-q` as its keyboard shortcut. Menu items are outside of our keymap system because they're handled by the OS, so this will probably need to be addressed by making a pass through all default bindings with menu items and changing their bindings.

Does anyone have a suggestion for a better default binding scheme on Windows? There really seems to be very little real estate.

**Comment by ccoenen** [comment]
There's another funny side-effect that I didn't test before:

On a german keyboard, there's no single key for `/`, so The Usual shortcut <kbd>Ctrl+Slash</kbd> (to comment out a block of selected code) is actually <kbd>Ctrl+Shift+7</kbd> - because `/` is <kbd>Shift+7</kbd>.

This shortcut did not work in atom 1.10, it does work in this version. That's a very welcome surprise!

**Comment by fractalf** [comment]
Hi, I'm on Linux with a [Norwegian keyboard (nb_NO)](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/KB_Norway.svg/2000px-KB_Norway.svg.png)

Everything works fine when writing code, but the Key Binding Resolver showes wrong keys. Problem is that some shortcuts are not working. Read a lot of threads, but couldn't get to the bottom of the problem

I'm willing to contribute to get this fixed, but not really sure what to do.

Cheers

**Comment by Ben3eeE** [comment]
@fractalf This should be fixed starting with Atom 1.12-beta. Contribution at this point would be to wait for beta and see if everything works 🎉

**Comment by fractalf** [comment]
@Ben3eeE I installed the 1.12-beta0 today and the issue remains. Did I miss some setting? Scanned the settings, but couldn't find any. Weird thing though, the actual CTRL+\ gave CTRL+] earlier. Now it shows CTRL+=.

**Comment by Ben3eeE** [comment]
Thanks for following up 🙇. There should not be any setting for this. Which OS are you on? In addition I can think of these questions.

1. Can you reproduce this in safe mode `atom --safe`? There might be some issues in combination with the `keyboard-localization` package which was previously recommended to resolved these issues.
2. Do you see these results in the keybinding resolver? <kbd>Ctrl+.</kbd>.
3. Did you make sure that your operating system is configured to the correct language settings?

/cc: @thomasjo Norsk layout.

**Comment by Ben3eeE** [comment]
I see in your comment ☝️ that you are on Linux, the exact version could still help. In addition to the above questions can you please also provide the following:

1. The output of `atom --version`
2. The output of `apm --version`

**Comment by fractalf** [comment]
Cheers for the follow-up, issue is not resolved, here's some more data..

```
> cat /proc/version
Linux version 4.4.0-38-generic (buildd@lgw01-58) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #57-Ubuntu SMP Tue Sep 6p 15:42:33 UTC 2016
> cat /etc/issue
Linux Mint 18 Sarah \n \l
> atom-beta --versionalf@samsung ~ $
Atom    : 1.12.0-beta0
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
> apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.1

```

Running `> atom-beta --safe` didn't help.

OK, this is quite weird. In the *Key Binding Resolver* this is what I get:

* pressing  <kbd>ctrl</kbd>,  seeing <kbd>ctrl</kbd>
* pressing  <kbd>&#92;</kbd>, seeing <kbd>&#92;</kbd>
* pressing  <kbd>ctrl</kbd>+<kbd>&#92;</kbd>, but seeing <kbd>ctrl</kbd>+<kbd>=</kbd>

My locale settings were a bit of, meaning they were set to Swedish (god help me), so I changed them to Norwegian, but that doesn't seem to have any impact either.
```
> locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=nb_NO.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=nb_NO.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=nb_NO.UTF-8
LC_NAME=nb_NO.UTF-8
LC_ADDRESS=nb_NO.UTF-8
LC_TELEPHONE=nb_NO.UTF-8
LC_MEASUREMENT=nb_NO.UTF-8
LC_IDENTIFICATION=nb_NO.UTF-8
LC_ALL=
```

..awaiting further instructions :)

**Comment by nathansobo** [comment]
It looks like Chrome is misreporting characters for modified keystrokes on Linux. We're going to need to access native APIs to build up a keymap to work around this issue, which will take a few more days. We won't push 1.12 to the stable channel until this is working correctly. Thanks for reporting!

**Comment by Stasimon** [comment]
@Ben3eeE #247

**Pull request merged**
