### PR TITLE
[WIP] Convert coffee to JS

### PR DESCRIPTION
**Pull request by Rokt33r**
- [ ] src
  - [x] command-event
  - [ ] helper
  - [x] key-binding
  - [ ] keymap-manager
  - [x] us-keymap
- [ ] spec
  - [ ] helpers-spec
  - [ ] key-binding-spec
  - [ ] keymap-manager-spec
- [ ] benchmark/benchmark
- [ ] gruntfile
- [ ] remove all dependencies related with coffee script

### CODE REVIEW

**Comment by thomasjo** [comment]
Remember to remove the original CoffeeScript implementation when you convert a module/file.

**Comment by Rokt33r** [comment]
@thomasjo Sorry, I deleted them locally, but didn't include to the commits.

**Comment by Rokt33r** [comment]
I need a feedback to proceed my work. Is it okay not to be hurry?  🤔

**Comment by nathansobo** [comment]
>  need a feedback to proceed my work. Is it okay not to be hurry?  🤔

What sort of feedback do you need? This module has been churning quite a bit due to fallout from the changes to support international bindings. Once that settles down I don't anticipate it changing nearly as much, so you should be able to proceed at a slower pace without hitting tons of conflicts. Sorry, this was a tough time to attempt this conversion but it should be settling down soon.

**Comment by Rokt33r** [comment]
It's okay. I just want to check. :smile: 
I'll try to find where I can give you help for international bindings.

**Comment by nathansobo** [comment]
> I'll try to find where I can give you help for international bindings.

We're almost there with that I hope.

**Comment by Ben3eeE** [comment]
@Rokt33r Are you still interested in finishing this PR?

**Comment by Rokt33r** [comment]
Sorry, I have no time to deal with this. 😢

**Pull request closed without merging**
